# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43db9c3332b99a4d7adf7ddbf100cf099ede914656c0d654d3bf406b6c6c7930854daf8dab8feeea0a13fff51d1c3f9d446f91fbe0104dc310d499281f517c98

test:
  secret_key_base: a6ccaa29f9ab0822b1281e7856cea0e9ac3a882003defef21f65ff6db5387c0c508586e4b400968217f9f4fb0026f10e5bd12b78d8559f57a924068ef393d73c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
